//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWRClientWebInterface.Controls {
    
    
    public partial class CtlTaskSpecific {
        
        /// <summary>
        /// ctlCommonTaskDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MWRClientWebInterface.Controls.CommonTaskDetails ctlCommonTaskDetails;
        
        /// <summary>
        /// ctlCommonDetailsToAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MWRClientWebInterface.Controls.CommonDetailsToAdd ctlCommonDetailsToAdd;
        
        /// <summary>
        /// ctlTskKillProcess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MWRClientWebInterface.Controls.CtlTaskKillProcess ctlTskKillProcess;
        
        /// <summary>
        /// ctlTskRunProcess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MWRClientWebInterface.Controls.CtlTaskRunProcess ctlTskRunProcess;
        
        /// <summary>
        /// ctlTskMakeScreenShoot control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MWRClientWebInterface.Controls.CtlTaskMakeScreenshoot ctlTskMakeScreenShoot;
        
        /// <summary>
        /// btSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btSave;
        
        /// <summary>
        /// btRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btRefresh;
        
        /// <summary>
        /// hdCreateMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdCreateMode;
        
        /// <summary>
        /// hdTaskGuid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdTaskGuid;
    }
}
